all: interprocess_communication

interprocess_communication : interprocess_communication.c
	gcc -o interprocess_communication interprocess_communication.c

.PHONY: clean
clean:
	rm interprocess_communication
